# Generated by Django 3.1.5 on 2021-02-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('', 'Choose category'), ('ft', 'Football'), ('bs', 'Basketball'), ('sj', 'Ski Jumping'), ('hb', 'Handball'), ('bx', 'Boxing'), ('vb', 'Volleyball')], default='', max_length=2),
        ),
    ]
